### ISSUE TITLE
Throws Error when no arguments supplied

### ISSUE THREAD

**Issue by aidanheerdegen** [coecms/dusql#31]
When no argument is supplied `dusql` reports `AttributeError`
```
$ dusql
Traceback (most recent call last):
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/bin/dusql", line 12, in <module>
    sys.exit(main())
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/grafanadb/cli.py", line 41, in main
    if args.run is not None:
AttributeError: 'Namespace' object has no attribute 'run'
```
```
# Name                    Version                   Build  Channel
dusql                     0.4                pyh14c3975_0    coecms
```

**Comment by ScottWales** [comment]
Fixed for next release
