### ISSUE TITLE
Proxy Error running ncdu on large directory

### ISSUE THREAD

**Issue by aidanheerdegen** [coecms/dusql#32]
Ran this 3 times, first 2 times seemed to freeze, and then got this error:
```
$ dusql ncdu /short/v45
Traceback (most recent call last):
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/bin/dusql", line 12, in <module>
    sys.exit(main())
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/grafanadb/cli.py", line 42, in main
    args.run(args)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/grafanadb/cli.py", line 129, in run
    curses.wrapper(ncdu.main, args.path[0], f_args)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/grafanadb/ncdu.py", line 158, in main
    state = State(stdscr, root, find_args)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/grafanadb/ncdu.py", line 48, in __init__
    self.chdir(".")
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/grafanadb/ncdu.py", line 66, in chdir
    r.raise_for_status()
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Proxy Error for url: https://accessdev-test.nci.org.au/dusql/du
````
worked ok the third time, same error 4th time.

**Comment by ScottWales** [comment]
This is because the database is timing out on a big query. Next release will set a 2 second time limit on queries, reporting `?` as the size and inode count if the query times out

**Comment by aidanheerdegen** [comment]
I'm not sure 2 seconds is long enough. The queries I was running would have not completed very much before returning `?`. Can it be a bit longer? 5 seconds?

**Comment by ScottWales** [comment]
It looks like the timeout on the database size defaults to 10 seconds, let's go with 8 to be a bit under that
