### ISSUE TITLE
ncdu: File not found error 

### ISSUE THREAD

**Issue by aidanheerdegen** [coecms/dusql#33]
Occurred when navigating down to `/short/v45/aph502/mom/input`
```
$ dusql ncdu /short/v45/aph502
Traceback (most recent call last):
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/bin/dusql", line 12, in <module>
    sys.exit(main())
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/grafanadb/cli.py", line 42, in main
    args.run(args)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/grafanadb/cli.py", line 129, in run
    curses.wrapper(ncdu.main, args.path[0], f_args)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/grafanadb/ncdu.py", line 167, in main
    state.update(c)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/grafanadb/ncdu.py", line 140, in update
    self.chdir(self.children[self.row - 1][0])
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/grafanadb/ncdu.py", line 61, in chdir
    (entry.stat().st_dev, entry.stat().st_ino)
FileNotFoundError: [Errno 2] No such file or directory: '/short/v45/aph502/mom/input/sis01_135'
```

**Comment by ScottWales** [comment]
Fixed for next release
